version: "3.2"

services:
  app:
    restart: always
    build: .
    expose:
      - "8020"
    ports:
      - 8000:8020
    env_file: ./webapp/.env
    volumes:
      - ./webapp:/app/webapp
    working_dir: /app/webapp
    command: >
      sh -c "gunicorn -w 4 ./webapp/main:app"

  mongo:
    image: mongo
    env_file: .env
  mongo-express:
    image: mongo-express
    env_file: .env
    ports:
      - "8080:8081"
